### ISSUE TITLE
V nově založené události jsou lidé, kteří se tam ještě ani nemohli registrovat

### ISSUE THREAD

**Issue by risa** [Tomucha/coordinator#10]
Nově založím událost - např. test tornáda 2 - ještě dřív než se kdokoliv mohl registrovat, tak už tam je řada uživatelů - Lucias, Admin Nobody, Kveta Przywarova apod. ....

**Comment by risa** [comment]
Ale zdá se, že pouze v serverové části ...

**Comment by Tomucha** [comment]
Ještě jeden lol. Opraveno v bb5309a
