### ISSUE TITLE
Do nově založené události "prosakují" POI z jiných událostí

### ISSUE THREAD

**Issue by risa** [Tomucha/coordinator#11]
Nově zalžená událost Event Test - ihned po založení tam mám identické POI jako v jiných událostech - typicky Excalibur v kanále!

Viz screenshot:

![image](https://cloud.githubusercontent.com/assets/1949242/3105829/b7eae4b8-e676-11e3-9be1-746d7aa22877.png)

**Comment by Tomucha** [comment]
Lol, sem pyča. Ale myslel jsem to dobře. Nicméně - je to opraveno v dfb9c6c

**Comment by risa** [comment]
To mě těší, že se u toho i bavíš ;-)
