### ISSUE TITLE
MOBILE: nelze instalovat aplikaci

### ISSUE THREAD

**Issue by anyz13** [Tomucha/coordinator#16]
Dnes stáhnutou verzi aplikace nelze nainstalovat na Androidu v4.1.2 Po otevření stažené apk zobrazí seznam oprávnění, ale tlačítko Instalovat nereaguje, Tlačítko Zrušit funguje. Instalace z neznámých zdrojů je povolena.

**Comment by risa** [comment]
Co je to konkrétně za přístroj? Nemůže tam být nějaký antivirus? Stáhle se
ten instalační balík správně? Má správnou velikost - mě se ukazuje 1 660
373 bytů, MD5 1B1AA4753BB6B4FC8A68D22582134A12?

R.

Dne 17. září 2014 10:29 anyz13 notifications@github.com napsal(a):

> Dnes stáhnutou verzi aplikace nelze nainstalovat na Androidu v4.1.2 Po
> otevření stažené apk zobrazí seznam oprávnění, ale tlačítko Instalovat
> nereaguje, Tlačítko Zrušit funguje. Instalace z neznámých zdrojů je
> povolena.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Tomucha/coordinator/issues/16.

## 

Richard Kořínek
^^^^^^^^^^^^^^
Člověk v tísni, o.p.s.
Litovelská 14
779 00 Olomouc
tel: +420 608 732 386

**Comment by anyz13** [comment]
Sony Xperia Go, model ST27i
Kompletně jsem vypnula avast - žádná změna
Instalační soubor stažen celý, hash sedí

**Comment by risa** [comment]
Poslední co mě napadá - komplet restart telefonu, jestli tam nezatuhnuly
nějaké aktualizační procesy. Potom už bude muset asi Tomucha ... jestli nás
tedy poslouchá ...

R.

Dne 17. září 2014 10:41 anyz13 notifications@github.com napsal(a):

> Sony Xperia Go, model ST27i
> Kompletně jsem vypnula avast - žádná změna
> Instalační soubor stažen celý, hash sedí
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Tomucha/coordinator/issues/16#issuecomment-55865021.

## 

Richard Kořínek
^^^^^^^^^^^^^^

**Comment by anyz13** [comment]
Už to mám - nechtěl instalovat na kartu. Ale restart byl pak taky potřebný.
Díky za spolupráci. Pokusím se v blízké době otestovat aktualizace (i na serverové části).
A.

**Comment by risa** [comment]
Díky moc!

R.

Dne 17. září 2014 11:08 anyz13 notifications@github.com napsal(a):

> Už to mám - nechtěl instalovat na kartu. Ale restart byl pak taky potřebný.
> Díky za spolupráci. Pokusím se v blízké době otestovat aktualizace (i na
> serverové části).
> A.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Tomucha/coordinator/issues/16#issuecomment-55867717.

## 

Richard Kořínek
^^^^^^^^^^^^^^
