### ISSUE TITLE
Error in address search

### ISSUE THREAD

**Issue by risa** [Tomucha/coordinator#2]
java.lang.NullPointerException
    at cz.clovekvtisni.coordinator.server.web.controller.EventMapController.addressSearch(EventMapController.java:73)

JsonNode node = objectMapper.readTree(data); 

Obviously when the search returns no address ...

**Comment by Tomucha** [comment]
Tak to by bylo opravene.

Takova jako rozcvicka, rozbehani projektu na novym NTB a tak.
