### ISSUE TITLE
Vytvoření skupiny

### ISSUE THREAD

**Issue by risa** [Tomucha/coordinator#3]
Skončí na chybové hlášce ERROR: NOT_FOUND, 

URL: http://coordinator-test.appspot.com/admin/event/user-group/?eventId=5815162380484608&helpId=eventusergroupedit&canDoLogout=true&now=1396517649296

**Comment by Tomucha** [comment]
Ano, ale jen kdyz se slo ze seznamu uzivatelu, coz cinilo chybu obtizne nalezitelnou.
