### ISSUE TITLE
SERVER - smazání POI přesměruje na chybovou stránku Error: NOT_FOUND

### ISSUE THREAD

**Issue by risa** [Tomucha/coordinator#7]
POI se smaže. 

URL předmětné stránky, jež nebyla nalezena,  je: http://coordinator-test.appspot.com/admin/event/poi/%20/admin/event/poi/list?eventId=5858956014518272&helpId=eventpoilist&canDoLogout=true&selectedPoiActions=DELETE&now=1401285059043

**Comment by Tomucha** [comment]
Noooo tohle se mi taky nepodarilo navodit, ale snad se mi to podarilo opravit, ješto to bylo o překlepné mezeře ve výsledném redirectu. Prauděpodobně to záviselo aj na prohlížeču.
