### ISSUE TITLE
Nelogické chování při založení nové události

### ISSUE THREAD

**Issue by risa** [Tomucha/coordinator#8]
Popis:

Jako uživatel admin@matelier.cz vytvořím událost -  Test tornáda 2 - vlezu do události, doplním potřebné informace - publish date a potom se nedostanu jinam, než na stránku Update user, mám editovat sám sebe, přičemž není jasné proč tam jsem a pokud  tam má něco zadat, tak co.
Nakonec pomohlo zadání telefonního čísla, případně stačí jen Save data"

**Comment by Tomucha** [comment]
Tož - toto je tam proto, že každý musí mít v události záznam, jináče s ní nemůže pracovat. A v každé události může být záznam odlišný. Tak jsme si to "zanalyzovali".

Navrhuju vyřešit proškolením adminů - když poprvé lezete do události musíte aktualizovat profil. A doplněním této hlášky.

Jiná varianta, která by se mi líbila víc, by bylo to překopat, obsah registrace v události omezit na pouhé "ano, jsem v události" a to vyplňovat automaticky. Ale to je netriviální úprava, zvící cca 4-6 hodin (zasahuje to i do mobilu).

**Comment by Tomucha** [comment]
Pridany vysvetlivky v faf2c74
